if Debug then Debug.beginFile "Game/Stations/ST11/ST11Init" end
OnInit.map("ST11Init", function(require)
    function Trig_ST11Init_Func016A()
        CreateFogModifierRectBJ(true, GetEnumPlayer(), FOG_OF_WAR_VISIBLE, gg_rct_ST11V1)
        DestroyFogModifier(GetLastCreatedFogModifier())
        CreateFogModifierRectBJ(true, GetEnumPlayer(), FOG_OF_WAR_VISIBLE, gg_rct_ST11V10)
        DestroyFogModifier(GetLastCreatedFogModifier())
        CreateFogModifierRectBJ(true, GetEnumPlayer(), FOG_OF_WAR_VISIBLE, gg_rct_ST11V11)
        DestroyFogModifier(GetLastCreatedFogModifier())
        CreateFogModifierRectBJ(true, GetEnumPlayer(), FOG_OF_WAR_VISIBLE, gg_rct_ST11V12)
        DestroyFogModifier(GetLastCreatedFogModifier())
        CreateFogModifierRectBJ(true, GetEnumPlayer(), FOG_OF_WAR_VISIBLE, gg_rct_ST11V13)
        DestroyFogModifier(GetLastCreatedFogModifier())
        CreateFogModifierRectBJ(true, GetEnumPlayer(), FOG_OF_WAR_VISIBLE, gg_rct_ST11V14)
        DestroyFogModifier(GetLastCreatedFogModifier())
        CreateFogModifierRectBJ(true, GetEnumPlayer(), FOG_OF_WAR_VISIBLE, gg_rct_ST11V15)
        DestroyFogModifier(GetLastCreatedFogModifier())
        CreateFogModifierRectBJ(true, GetEnumPlayer(), FOG_OF_WAR_VISIBLE, gg_rct_ST11V16)
        DestroyFogModifier(GetLastCreatedFogModifier())
        CreateFogModifierRectBJ(true, GetEnumPlayer(), FOG_OF_WAR_VISIBLE, gg_rct_ST11V17)
        DestroyFogModifier(GetLastCreatedFogModifier())
        CreateFogModifierRectBJ(true, GetEnumPlayer(), FOG_OF_WAR_VISIBLE, gg_rct_ST11V18)
        DestroyFogModifier(GetLastCreatedFogModifier())
        CreateFogModifierRectBJ(true, GetEnumPlayer(), FOG_OF_WAR_VISIBLE, gg_rct_ST11V19)
        DestroyFogModifier(GetLastCreatedFogModifier())
        CreateFogModifierRectBJ(true, GetEnumPlayer(), FOG_OF_WAR_VISIBLE, gg_rct_ST11V2)
        DestroyFogModifier(GetLastCreatedFogModifier())
        CreateFogModifierRectBJ(true, GetEnumPlayer(), FOG_OF_WAR_VISIBLE, gg_rct_ST11V20)
        DestroyFogModifier(GetLastCreatedFogModifier())
        CreateFogModifierRectBJ(true, GetEnumPlayer(), FOG_OF_WAR_VISIBLE, gg_rct_ST11V21)
        DestroyFogModifier(GetLastCreatedFogModifier())
        CreateFogModifierRectBJ(true, GetEnumPlayer(), FOG_OF_WAR_VISIBLE, gg_rct_ST11V22)
        DestroyFogModifier(GetLastCreatedFogModifier())
        CreateFogModifierRectBJ(true, GetEnumPlayer(), FOG_OF_WAR_VISIBLE, gg_rct_ST11V23)
        DestroyFogModifier(GetLastCreatedFogModifier())
        CreateFogModifierRectBJ(true, GetEnumPlayer(), FOG_OF_WAR_VISIBLE, gg_rct_ST11V24)
        DestroyFogModifier(GetLastCreatedFogModifier())
        CreateFogModifierRectBJ(true, GetEnumPlayer(), FOG_OF_WAR_VISIBLE, gg_rct_ST11V3)
        DestroyFogModifier(GetLastCreatedFogModifier())
        CreateFogModifierRectBJ(true, GetEnumPlayer(), FOG_OF_WAR_VISIBLE, gg_rct_ST11V4)
        DestroyFogModifier(GetLastCreatedFogModifier())
        CreateFogModifierRectBJ(true, GetEnumPlayer(), FOG_OF_WAR_VISIBLE, gg_rct_ST11V5)
        DestroyFogModifier(GetLastCreatedFogModifier())
        CreateFogModifierRectBJ(true, GetEnumPlayer(), FOG_OF_WAR_VISIBLE, gg_rct_ST11V6)
        DestroyFogModifier(GetLastCreatedFogModifier())
        CreateFogModifierRectBJ(true, GetEnumPlayer(), FOG_OF_WAR_VISIBLE, gg_rct_ST11V7)
        DestroyFogModifier(GetLastCreatedFogModifier())
        CreateFogModifierRectBJ(true, GetEnumPlayer(), FOG_OF_WAR_VISIBLE, gg_rct_ST11V8)
        DestroyFogModifier(GetLastCreatedFogModifier())
        CreateFogModifierRectBJ(true, GetEnumPlayer(), FOG_OF_WAR_VISIBLE, gg_rct_ST11V9)
        DestroyFogModifier(GetLastCreatedFogModifier())
    end

    function Trig_ST11Init_Actions()
        DestroyTrigger(GetTriggeringTrigger())
        EnableTrigger(gg_trg_ST11BloodEffect)
        EnableTrigger(gg_trg_ST11HivesDie)
        EnableTrigger(gg_trg_ST11DieNatural)
        udg_Sector_Space[27] = GetLastCreatedUnit()
        udg_All_Dock[53] = gg_dest_B009_5548
        udg_All_Dock[54] = gg_dest_B009_5547
        udg_All_Dock[55] = gg_dest_B009_5543
        udg_All_Dock[56] = gg_dest_B009_5542
        udg_All_Dock[57] = gg_dest_B009_5540
        udg_SectorId[27] = gg_rct_OverlordRect
        udg_TempUnit = GetLastCreatedUnit()
        GroupAddUnitSimple(udg_TempUnit, udg_SpaceObject_CollideGroup)
        NewUnitRegister(udg_TempUnit)
        udg_SpaceObject_CollideRadius[GetUnitUserData(udg_TempUnit)] = 150.00
        ForForce(GetPlayersAll(), Trig_ST11Init_Func016A)
        PlaySoundBJ(gg_snd_SargerasRoar02)
        UnitRemoveAbilityBJ(FourCC('Avul'), gg_unit_h04X_0172)
        UnitRemoveAbilityBJ(FourCC('Avul'), gg_unit_h04X_0148)
        UnitRemoveAbilityBJ(FourCC('Avul'), gg_unit_h04X_0173)
    end

    --===========================================================================
    gg_trg_ST11Init = CreateTrigger()
    TriggerAddAction(gg_trg_ST11Init, Trig_ST11Init_Actions)
end)
if Debug then Debug.endFile() end
